import Link from "next/link";

export const metadata = {
    title: "Terms & Conditions — QuitSugar",
    description: "Read the Terms and Conditions for using QuitSugar, an AI-powered image generation platform.",
};

const LAST_UPDATED = "February 22, 2026";
const APP_NAME = "QuitSugar";
const CONTACT_EMAIL = "support@quitsugar.app";

const sections = [
    {
        id: "acceptance",
        title: "1. Acceptance of Terms",
        content: `By accessing or using ${APP_NAME} ("the Service", "we", "our", or "us"), you confirm that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service. Your continued use of the platform constitutes acceptance of any future updates to these terms.`,
    },
    {
        id: "description",
        title: "2. Description of Service",
        content: `${APP_NAME} is an AI-powered image generation tool that creates visual transformations based on user-submitted photographs and lifestyle inputs (such as number of days without sugar). The platform uses artificial intelligence and machine learning models to produce illustrative, speculative images of potential physical changes over time.`,
    },
    {
        id: "ai-disclaimer",
        title: "3. AI-Generated Content Disclaimer",
        content: null,
        subsections: [
            {
                title: "3.1 Speculative Nature of Results",
                body: `All images, transformations, and visual outputs produced by ${APP_NAME} are entirely AI-generated and speculative in nature. They are artistic representations only and do not reflect guaranteed, promised, or predicted real-world outcomes for any individual.`,
            },
            {
                title: "3.2 Not Medically Accurate",
                body: `The results generated by this Service are NOT medically accurate. They should not be interpreted as medical advice, clinical assessment, diagnostic information, or a substitute for professional healthcare consultation. The Service makes no claim that AI-generated transformations reflect scientifically validated health outcomes.`,
            },
            {
                title: "3.3 AI Limitations & Ongoing Learning",
                body: `Our AI models are continuously being trained and improved. Like all machine learning systems, they can and do make mistakes. Outputs may contain inaccuracies, unrealistic portrayals, or unexpected results. We are actively working to improve accuracy and quality, but we cannot guarantee perfect results at this stage of development.`,
            },
            {
                title: "3.4 Individual Results Vary",
                body: `Physical results from lifestyle changes, including reducing or eliminating sugar consumption, vary greatly between individuals based on genetics, overall diet, medical conditions, and many other factors. No AI-generated image can predict your personal outcome.`,
            },
            {
                title: "3.5 Individual Results Vary",
                body: `Physical results from lifestyle changes, including reducing or eliminating sugar consumption, vary greatly between individuals based on genetics, overall diet, medical conditions, and many other factors. No AI-generated image can predict your personal outcome.`,
            },
        ],
    },
    {
        id: "health-warning",
        title: "4. Health & Medical Warning",
        content: null,
        highlight: true,
        subsections: [
            {
                title: "4.1 Not a Medical Device",
                body: `${APP_NAME} is not a medical device, healthcare application, or clinical tool. It is an entertainment and motivational platform only. Nothing on this platform constitutes medical advice.`,
            },
            {
                title: "4.2 Consult a Professional",
                body: `Before making any significant changes to your diet, sugar intake, or lifestyle, you should consult a qualified healthcare professional, registered dietitian, or licensed physician. Do not use AI-generated images as the basis for any health decisions.`,
            },
            {
                title: "4.3 Mental Health Consideration",
                body: `AI-generated body transformations may affect users differently. If you have a history of body image concerns, eating disorders, or related mental health conditions, please use this platform with caution and seek professional guidance as needed.`,
            },
        ],
    },
    {
        id: "user-content",
        title: "5. User-Submitted Content",
        content: null,
        subsections: [
            {
                title: "5.1 Photo Uploads",
                body: `By uploading a photograph to the Service, you confirm that you own the rights to that image and that you consent to its temporary processing by our AI systems for the purpose of generating a transformation result.`,
            },
            {
                title: "5.2 Data Handling",
                body: `Uploaded images are processed solely to generate your requested output. We do not use your photos to train our models without explicit consent, and we do not sell your images to third parties. Please refer to our Privacy Policy for full details on data handling.`,
            },
            {
                title: "5.3 Prohibited Content",
                body: `You must not upload images of minors, images belonging to others without permission, explicit content, or any content that violates applicable laws. Violations may result in immediate termination of your account.`,
            },
        ],
    },
    {
        id: "intellectual-property",
        title: "6. Intellectual Property",
        content: `The ${APP_NAME} platform, its design, underlying technology, branding, and all non-user-generated content are the intellectual property of ${APP_NAME} and its licensors. AI-generated output images created using your uploaded photo are made available to you for personal, non-commercial use. You may not use them for commercial purposes without prior written consent.`,
    },
    {
        id: "limitation-liability",
        title: "7. Limitation of Liability",
        content: `To the fullest extent permitted by applicable law, ${APP_NAME} shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from: (a) your use or reliance on AI-generated images; (b) inaccuracies in generated content; (c) health or lifestyle decisions made based on platform outputs; or (d) any technical errors, service interruptions, or data loss. Your use of the Service is entirely at your own risk.`,
    },
    {
        id: "no-warranty",
        title: "8. No Warranty",
        content: `The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that results will be accurate, reliable, or meet your expectations.`,
    },
    {
        id: "account",
        title: "9. User Accounts",
        content: `You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use. We reserve the right to suspend or terminate accounts that violate these Terms.`,
    },
    {
        id: "changes",
        title: "10. Changes to Terms",
        content: `We reserve the right to update or modify these Terms at any time. Changes will be posted on this page with a revised "Last Updated" date. Your continued use of the Service after any changes constitutes your acceptance of the new Terms. We encourage you to review these Terms periodically.`,
    },
    {
        id: "governing-law",
        title: "11. Governing Law",
        content: `These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which ${APP_NAME} operates, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts in that jurisdiction.`,
    },
    {
        id: "contact",
        title: "12. Contact Us",
        content: `If you have any questions, concerns, or feedback about these Terms and Conditions, please contact us at:`,
        email: CONTACT_EMAIL,
    },
];

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-white text-black font-sans relative overflow-hidden">

            {/* Ambient blobs */}
            <div className="absolute top-[-10%] right-[-10%] w-[50%] h-[30%] bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 rounded-full blur-[120px] opacity-60 pointer-events-none" />
            <div className="absolute bottom-[-5%] left-[-10%] w-[45%] h-[25%] bg-gradient-to-tr from-emerald-50 to-teal-50 rounded-full blur-[100px] opacity-50 pointer-events-none" />

            {/* Header */}
            <header className="relative z-10 border-b border-neutral-100 bg-white/80 backdrop-blur-sm sticky top-0">
                <div className="max-w-3xl mx-auto px-5 sm:px-8 py-4 flex items-center justify-between">
                    <Link href="/" className="inline-flex items-center gap-2.5 group">
                        <div className="flex items-center justify-center w-8 h-8 rounded-xl bg-black shadow-sm group-hover:scale-105 transition-transform duration-150">
                            <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 3c-1.5 3-4 5-4 8a4 4 0 008 0c0-3-2.5-5-4-8z" />
                            </svg>
                        </div>
                        <span className="text-[15px] font-semibold text-neutral-900">{APP_NAME}</span>
                    </Link>
                    <Link
                        href="/signup"
                        className="text-[13px] font-medium text-neutral-500 hover:text-neutral-900 transition-colors underline underline-offset-2 decoration-transparent hover:decoration-neutral-300"
                    >
                        ← Back to Sign Up
                    </Link>
                </div>
            </header>

            {/* Page Content */}
            <div className="relative z-10 max-w-3xl mx-auto px-5 sm:px-8 py-10 sm:py-16">

                {/* Page Title */}
                <div className="mb-10 sm:mb-14">
                    <div className="inline-flex items-center gap-2 bg-neutral-100 text-neutral-500 text-[11px] font-semibold uppercase tracking-widest px-3 py-1.5 rounded-full mb-5">
                        <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        Legal
                    </div>
                    <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-neutral-900 leading-tight mb-4">
                        Terms & Conditions
                    </h1>
                    <p className="text-[15px] text-neutral-500 leading-relaxed">
                        Please read these terms carefully before using {APP_NAME}. By using our service, you agree to these terms.
                    </p>
                    <p className="mt-3 text-[13px] text-neutral-400">
                        Last updated: <span className="font-medium text-neutral-500">{LAST_UPDATED}</span>
                    </p>
                </div>

                {/* AI Disclaimer Banner */}
                <div className="mb-10 p-5 rounded-2xl border border-amber-200 bg-amber-50">
                    <div className="flex gap-3.5">
                        <div className="flex-shrink-0 mt-0.5">
                            <svg className="w-5 h-5 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-[14px] font-semibold text-amber-800 mb-1">Important Notice</p>
                            <p className="text-[13px] text-amber-700 leading-relaxed">
                                {APP_NAME} generates AI-powered images that are <strong>not medically accurate</strong> and should <strong>not</strong> be used as medical advice. Our AI is still learning and may produce inaccurate results. Always consult a qualified healthcare professional before making health decisions.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Table of Contents */}
                <div className="mb-10 p-5 rounded-2xl border border-neutral-100 bg-neutral-50">
                    <p className="text-[11px] font-semibold uppercase tracking-widest text-neutral-400 mb-3">Contents</p>
                    <nav className="flex flex-col gap-1.5">
                        {sections.map((s) => (
                            <a
                                key={s.id}
                                href={`#${s.id}`}
                                className="text-[13px] text-neutral-600 hover:text-neutral-900 transition-colors hover:underline underline-offset-2"
                            >
                                {s.title}
                            </a>
                        ))}
                    </nav>
                </div>

                {/* Sections */}
                <div className="space-y-10">
                    {sections.map((section) => (
                        <section key={section.id} id={section.id} className="scroll-mt-20">
                            <h2 className="text-[18px] sm:text-[20px] font-bold text-neutral-900 mb-3 leading-snug">
                                {section.title}
                            </h2>

                            {/* Highlighted section (health warning) */}
                            {section.highlight && !section.content && (
                                <div className="rounded-xl border border-red-100 bg-red-50 p-5 mb-4">
                                    <div className="flex gap-2.5 mb-3">
                                        <svg className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                            <path strokeLinecap="round" strokeLinejoin="round" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                                        </svg>
                                        <p className="text-[13px] font-semibold text-red-700">This section contains critical health information.</p>
                                    </div>
                                    {section.subsections?.map((sub) => (
                                        <div key={sub.title} className="mb-4 last:mb-0">
                                            <h3 className="text-[14px] font-semibold text-red-800 mb-1">{sub.title}</h3>
                                            <p className="text-[14px] text-red-700 leading-relaxed">{sub.body}</p>
                                        </div>
                                    ))}
                                </div>
                            )}

                            {/* Regular content */}
                            {section.content && (
                                <p className="text-[15px] text-neutral-600 leading-relaxed">{section.content}</p>
                            )}

                            {/* Contact email */}
                            {section.email && (
                                <a
                                    href={`mailto:${section.email}`}
                                    className="inline-flex items-center gap-2 mt-3 text-[14px] font-medium text-neutral-900 underline underline-offset-2 decoration-neutral-300 hover:decoration-neutral-800 transition-all"
                                >
                                    <svg className="w-4 h-4 text-neutral-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                                    </svg>
                                    {section.email}
                                </a>
                            )}

                            {/* Non-highlighted subsections */}
                            {section.subsections && !section.highlight && (
                                <div className="space-y-5 mt-2">
                                    {section.subsections.map((sub) => (
                                        <div key={sub.title} className="pl-4 border-l-2 border-neutral-100">
                                            <h3 className="text-[14px] font-semibold text-neutral-800 mb-1.5">{sub.title}</h3>
                                            <p className="text-[14px] text-neutral-600 leading-relaxed">{sub.body}</p>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </section>
                    ))}
                </div>

                {/* Bottom Divider */}
                <div className="mt-16 pt-8 border-t border-neutral-100 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <p className="text-[12px] text-neutral-400">
                        © {new Date().getFullYear()} {APP_NAME}. All rights reserved.
                    </p>
                    <div className="flex items-center gap-4 text-[12px] text-neutral-400">
                        <Link href="/privacy" className="hover:text-neutral-600 transition-colors underline underline-offset-2 decoration-neutral-200">
                            Privacy Policy
                        </Link>
                        <span>·</span>
                        <Link href="/signup" className="hover:text-neutral-600 transition-colors underline underline-offset-2 decoration-neutral-200">
                            Sign Up
                        </Link>
                        <span>·</span>
                        <Link href="/login" className="hover:text-neutral-600 transition-colors underline underline-offset-2 decoration-neutral-200">
                            Log In
                        </Link>
                    </div>
                </div>

            </div>
        </main>
    );
}
